export const MakeInvestmentData = [
  {
    name:"1",
    img: "/images/investment/img-3.png",
    type: "• CLASS I •",
    arr: "4.5%",
    require: "1,000 SF",
    link: "class1",
    invested: "1,000 SF",
    rate: "4.5%",
    profit: "45 SF/month",
    insurance: "45 SF/month",
    servers: "1",
    proxies: "480",
    account: "480",
    thread: "480",
    video: "4,000",
    software: "6 months free",
    swapfee: "6 months free",
    systemfee: "12 months free",
  },
  {
    name:"2",
    img: "/images/investment/img-2.png",
    type: "• CLASS II •",
    arr: "4%",
    require: "1,000 SF",
    link: "class2",
    invested: "1,000 SF",
    rate: "4%",
    profit: "200 SF/month",
    insurance: "200 SF/month",
    servers: "5",
    proxies: "2,400",
    account: "2,400",
    thread: "2,400",
    video: "20,000",
    software: "6 months free",
    swapfee: "6 months free",
    systemfee: "12 months free",
  },
  {
    name:"3",
    img: "/images/investment/img-1.png",
    type: "• CLASS III •",
    arr: "3.5%",
    require: "1,000 SF",
    link: "class3",
    invested: "1,000 SF",
    rate: "3.5%",
    profit: "350 SF/month",
    insurance: "350 SF/month",
    servers: "10",
    proxies: "4,800",
    account: "4,800",
    thread: "4,800",
    video: "40,000",
    software: "Free",
    swapfee: "Free",
    systemfee: "12 months free",
  },
  {
    name:"4",
    img: "/images/investment/img-4.png",
    type: "• CLASS VI •",
    arr: "3%",
    require: "1,000 SF",
    link: "class4",
    invested: "1,000 SF",
    rate: "4.5%",
    profit: "1,500 SF/month",
    insurance: "1,500 SF/month",
    servers: "50",
    proxies: "24,000",
    account: "24,000",
    thread: "24,000",
    video: "200,000",
    software: "Free",
    swapfee: "Free",
    systemfee: "12 months free",
  },
];
